-- Import asset types from asset_types_latest.xlsx
-- Generated on 2026-02-01 16:15:19

-- Clear existing data (optional - comment out if you want to keep existing data)
-- DELETE FROM asset_types;

-- Insert all asset types from Excel
INSERT INTO asset_types (name, description, tax_region, area_description_for_tab, elevator, single_double_family, penthouse, condo, townhouses, business_residence, non_accountable_for_total_area, non_accountable_for_distribution, not_accountable_for_statistics, min_size, max_size) VALUES
  ('199', 'נכס משולב מגורים', 20, 'מגורים אזור 2', false, false, false, false, false, NULL, false, false, true, NULL, NULL),
  ('202', 'מגורים אזור 1 קו החוף', 10, NULL, false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('203', 'מגורים אזור 1 קו החוף', 10, NULL, false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('210', 'מגורים נכס לא ראוי לשימוש', 10, NULL, false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('211', 'מגורים אזור 1', 10, 'מגורים אזור 1', false, true, false, false, false, 'מגורים', false, false, false, 100, 9999),
  ('212', 'מגורים אזור 1', 10, 'מגורים אזור 1', false, true, false, false, false, 'מגורים', false, false, false, 1, 100),
  ('213', 'מגורים אזור 1', 10, 'מגורים אזור 1', false, false, false, true, false, 'מגורים', false, false, false, 111, 9999),
  ('214', 'מגורים אזור 1', 10, 'מגורים אזור 1', false, false, false, true, false, 'מגורים', false, false, false, 1, 110),
  ('216', 'מרפסת ללא חיוב', 10, 'מגורים אזור 1', false, false, false, false, false, 'מגורים', false, true, false, NULL, NULL),
  ('221', 'מגורים אזור 2', 20, 'מגורים אזור 2', false, true, false, false, false, 'מגורים', false, false, false, 100, 9999),
  ('222', 'מגורים אזור 2', 20, 'מגורים אזור 2', false, true, false, false, false, 'מגורים', false, false, false, 1, 100),
  ('223', 'מגורים אזור 2', 20, 'מגורים אזור 2', false, false, false, true, false, 'מגורים', false, false, false, 111, 9999),
  ('224', 'מגורים אזור 2', 20, 'מגורים אזור 2', false, false, false, true, false, 'מגורים', false, false, false, 1, 110),
  ('226', 'מרפסת ללא חיוב', 20, 'מגורים אזור 2', false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('231', 'מגורים אזור 3', 30, 'מגורים אזור 3', false, true, false, false, false, 'מגורים', false, false, false, 100, 9999),
  ('232', 'מגורים אזור 3', 30, 'מגורים אזור 3', false, true, false, false, false, 'מגורים', false, false, false, 1, 100),
  ('233', 'מגורים אזור 3', 30, 'מגורים אזור 3', false, false, false, true, false, 'מגורים', false, false, false, 111, 9999),
  ('234', 'מגורים אזור 3', 30, 'מגורים אזור 3', false, false, false, true, false, 'מגורים', false, false, false, 1, 110),
  ('236', 'מרפסת ללא חיוב', 30, 'מגורים אזור 3', false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('241', 'מגורים אזור 32', 32, NULL, false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('242', 'מגורים אזור 32', 32, NULL, false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('243', 'מגורים אזור 32', 32, NULL, false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('244', 'מגורים אזור 32', 32, NULL, false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('245', 'מגורים אזור 32', 32, NULL, false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('250', 'מחסן מגורים אזור 1', 10, 'מגורים אזור 1', false, false, false, false, false, 'מגורים', false, true, false, NULL, NULL),
  ('251', 'מגורים אזור 1', 10, 'מגורים אזור 1', false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('252', 'מחסן מגורים אזור 2', 20, 'מגורים אזור 2', false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('253', 'מגורים אזור 2', 20, 'מגורים אזור 2', false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('254', 'מחסן מגורים אזור 3', 30, 'מגורים אזור 3', false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('255', 'מגורים אזור 3', 30, 'מגורים אזור 3', false, false, false, false, false, 'מגורים', false, false, false, NULL, NULL),
  ('299', 'נכס משולב עסקים אזור 2', 50, 'עסקים אזור 2', false, false, false, false, false, 'עסקים', false, false, true, NULL, NULL),
  ('301', 'מסחר מעל 15,000 מ"ר', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('302', 'מבנה מכללות ואונברסיטאות', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('310', 'משרדים שרותים ומסחר לא ראוי', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('311', 'משרדים שרותים ומסחר אזור 1', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('312', 'משרדים שרותים ומסחר אזור 1', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('313', 'משרדי ממשלה אזור 1', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('315', 'מסחר ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('316', 'לא ראוי עפ"י סעיף 330 תעשיה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('317', 'לא ראוי עפ"י סעיף 330 מסחר', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('318', 'לא ראוי עפ"י סעיף 330 מגורים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('321', 'משרדים שרותים ומסחר אזור 2', 50, 'עסקים אזור 2', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('322', 'משרדים שרותים ומסחר אזור 2', 50, 'עסקים אזור 2', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('323', 'משרדי ממשלה אזור 2', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('325', 'פינוי בינוי', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('390', 'תיעול איחוד כרטיסים עסקים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('397', 'כרטיס בבניה למעקב עסקים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('398', 'היה בסוג נכס 400 נבדק וחוייבו', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('399', 'תעשיה ומלאכה לא ראוי לשימוש', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('400', 'כרטיס לבניה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('401', 'תעשיה ומלאכה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('402', 'עסיס תעשיה ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('403', 'אורדן תעשיה ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('404', 'תעשית טמפו ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('405', 'גמיד תעשיה ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('406', 'המסלול תעשיה ללא חיו', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('407', 'פרגוד תעשיה ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('408', 'פולידור ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('409', 'צינומנטל ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('410', 'שלרינה תעשיה ללא חיו', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('411', 'מפעלי שנפ - ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('412', 'אביק תעשיה ללא חיוב', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('413', 'נכסי מדינה תעשיה ומלאכה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('414', 'תעשיה עתירת ידע', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('415', 'נכס המשמש מספרה,קוסמטיקה אזור1', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('416', 'נכס המשמש מספרה,קוסמטיקה אזור2', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('417', 'מפעלי בטון ,מלט טיט וכו''', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('418', 'מעטפת עסקים אזור 2', 50, NULL, false, false, false, false, false, NULL, false, false, false, NULL, NULL),
  ('501', 'מוסדות אזור 1', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('502', 'מוסדות אזור 2', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('503', 'שכירות עירית נתניה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('504', 'רכוש עירית נתניה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('505', 'מוסד חינוך עירוני', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('506', 'גני נוי עירוניים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('507', 'מוסדות דת', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('508', 'אגודות ספורט', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('509', 'מוסדות אזור 1', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('510', 'מוסדות אזור 2', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('511', 'נכסי ממשלה אזור 1', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('512', 'נכסי ממשלה אזור 2', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('513', 'מפלגות', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('514', 'חל"ת', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('515', 'ללא סיווג דומה בצו הארנונה אז1', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('516', 'ללא סיווג דומה בצו הארנונה אז2', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('520', 'מקוואות', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('521', 'ישיבות - פנימיות', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('522', 'מוסד דת,חינוך ואחר', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('523', 'מים למוסדות', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('552', 'שלט לפי שטח', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('601', 'אדמה חקלאית', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('602', 'פרדסים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('603', 'ק.תפוסה תיעול', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('661', 'מיועד לביטול - פרדסים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('662', 'מיועד לביטול - חקלאית', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('700', 'קרקע לא בשימוש  עסקים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('701', 'ק.תפוסה לצרכי תעשיה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('702', 'ק.תפוסה לכל מטרה אחר', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('703', 'ק. תפוסה המשמש לעריכת ארועים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('704', 'ק. תפוסה למכירה/השכרה/החסנה וה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('705', 'קרקע תפוסהלשימוש מפעלי בטון וכ', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('800', 'רשת שווק מעל 1000 מ''', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('801', 'בנקים ומוסדות אשראי', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('802', 'בתי אריזה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('803', 'תחנות דלק', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('804', 'ק.תפוסה לתחנות דלק', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('805', 'מרכז קניות', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('806', 'בתי  קולנוע', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('807', 'גני-ילדים פרטיים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('808', 'בתי אבות', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('809', 'דוכן שוק', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('810', 'חניון לרכב מקורה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, true, false, NULL, NULL),
  ('811', 'חניון לא מקורה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, true, false, NULL, NULL),
  ('812', 'בתי-ספר פרטיים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('813', 'בי"ס ללא פיקוח מ.חינוך', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('814', 'חניון מעל 15000 מטר', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('815', 'חדרי טרנפורמציה חברת החשמל', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('816', 'חניון מקורה לא ראוי', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('818', 'שוק וייצמן', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('819', 'דוכן שוק קטן', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('820', 'דוכן שוק חדש', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('821', 'מנהלות מחוז בנקים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('822', 'בנקים תעריף מינימום', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('824', 'חברות ביטוח', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('827', 'מוזיאון למטרת רווח', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('828', 'מוזיאון ללא מטרת רווח', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('881', 'בית אבות אזור 1 מגורים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('882', 'בית אבות אזור 2 מגורים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('883', 'בית אבות אזור 3 מגורים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('901', 'בתי מלון עד 1000 מ"ר', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('902', 'בתי מלון מ-1,001 עד 2,000 מ"ר', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('903', 'בתי מלון מ-2,001 עד 4,000 מ"ר', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('904', 'בתי מלון  מ- 4,001 מטר ומעלה', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('905', 'בתי מלון 5 כוכבים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('906', 'דירות מיוחדות מגורים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('907', 'מעון למגורי עולים', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('908', 'אולמות כדורת', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('909', 'מרכז ספורט ונופש(קאנטרי קלאב)', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('910', 'מ. ספורט ונופש שטח פתוח', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('911', 'לא פעיל היה קופ"ח כללית', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('912', 'מבנה אצטדיון כדורגל', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('913', 'שטח קרקע פתוח של אצטדיון', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('915', 'בתי מלון נכס לא ראוי', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('990', 'ביטולים/איחודים', 990, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', true, true, true, 0, 0),
  ('995', 'נכס לא פעיל', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', false, false, false, NULL, NULL),
  ('999', 'נכס לצורך איזון', 40, 'עסקים אזור 1', false, false, false, false, false, 'עסקים', true, true, true, NULL, NULL);

-- Total rows inserted: 145
