#!/usr/bin/env bash
# Production deployment script for Ubuntu server.
# Run this script ON the production server (or via SSH) after cloning the repo.
#
# Prerequisites: Run as a user with sudo. PostgreSQL password will be prompted or set via PGPASSWORD.
#
# Usage:
#   # On the server (after cd to repo):
#   chmod +x scripts/deploy-production-ubuntu.sh
#   ./scripts/deploy-production-ubuntu.sh
#
#   # With custom DB password (set before running):
#   export PGPASSWORD='your_postgres_password'
#   export DB_PASSWORD='your_postgres_password'   # for app connection
#   ./scripts/deploy-production-ubuntu.sh
#
# Required env vars (or will prompt):
#   PGPASSWORD or DB_PASSWORD - PostgreSQL password for setup
#   SECRET_KEY - JWT secret (optional, will generate if not set)

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_USER="${SUDO_USER:-$USER}"
APP_NAME="buildingsmanager"
DB_NAME="${DB_NAME:-buildingsmanager}"
DB_USER="${DB_USER:-postgres}"
WEB_ROOT="/var/www/${APP_NAME}"

echo "=========================================="
echo "  AssetFlow / Buildings Manager - Production Deploy"
echo "  Ubuntu Server"
echo "=========================================="
echo ""

# --- 1. Gather configuration ---
if [ -z "${PGPASSWORD}" ] && [ -z "${DB_PASSWORD}" ]; then
  echo "Enter PostgreSQL password for user '$DB_USER' (used for DB setup):"
  read -s DB_PASSWORD_INPUT
  export PGPASSWORD="$DB_PASSWORD_INPUT"
  export DB_PASSWORD="$DB_PASSWORD_INPUT"
else
  export DB_PASSWORD="${DB_PASSWORD:-$PGPASSWORD}"
fi

# Generate SECRET_KEY if not set
if [ -z "$SECRET_KEY" ]; then
  SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
  echo "Generated SECRET_KEY for JWT (saved to backend/.env)"
fi

# --- 2. Install system packages ---
echo "[1/7] Installing system packages..."
sudo apt-get update
sudo apt-get install -y postgresql postgresql-contrib python3 python3-pip python3-venv nodejs npm nginx

# Ensure PostgreSQL is running
sudo systemctl start postgresql 2>/dev/null || true
sudo systemctl enable postgresql 2>/dev/null || true

# --- 3. Database setup ---
echo "[2/7] Setting up database..."
sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || true

# Create database if needed (using postgres superuser; peer auth)
sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME};" 2>/dev/null || echo "Database ${DB_NAME} may already exist."
sudo -u postgres psql -c "ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';" 2>/dev/null || true

# URL-encode password for connection string (# and @ break shell/URL parsing)
DB_PASS_URL=$(python3 -c "import urllib.parse,os; print(urllib.parse.quote(os.environ.get('DB_PASSWORD',''), safe=''))")
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS_URL}@localhost:5432/${DB_NAME}"

# Run migrations (use PGHOST=localhost to force TCP so password auth works)
echo "Applying migrations..."
cd "$REPO_ROOT"
export PGHOST=localhost
export DATABASE_URL
psql "$DATABASE_URL" -f "$REPO_ROOT/standalone/00_extensions_and_roles.sql"
chmod +x "$REPO_ROOT/standalone/apply_migrations.sh" 2>/dev/null || true
bash "$REPO_ROOT/standalone/apply_migrations.sh"
psql "$DATABASE_URL" -f "$REPO_ROOT/standalone/post_migration_standalone.sql"

# --- 4. Backend setup ---
echo "[3/7] Setting up Python backend..."
cd "$REPO_ROOT/backend"
python3 -m venv venv 2>/dev/null || true
source venv/bin/activate
pip install -r requirements.txt -q
# Fix bcrypt for passlib compatibility (login fails with newer bcrypt)
pip install 'bcrypt==4.0.1' -q

# Create .env for production
mkdir -p "$REPO_ROOT/backend/storage"
cat > "$REPO_ROOT/backend/.env" << EOF
# Production - generated by deploy-production-ubuntu.sh
DATABASE_URL=$DATABASE_URL
SECRET_KEY=$SECRET_KEY
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
STORAGE_PATH=$REPO_ROOT/backend/storage
STORAGE_MAIN_FOLDER=assetflow-files
STORAGE_USER=
STORAGE_PASSWORD=
ALLOWED_ORIGINS=http://localhost,http://127.0.0.1,http://185.229.226.37,http://185.229.226.37:80
ENVIRONMENT=production
EOF
echo "Backend .env created."

# --- 5. Create admin user ---
echo "[4/7] Creating admin user..."
if [ -f "$REPO_ROOT/backend/scripts/create_local_admin.py" ]; then
  python scripts/create_local_admin.py admin "ChangeMe123!" admin@assetflow.local admin 2>/dev/null || echo "Admin may already exist. Change password via script if needed."
else
  echo "Run manually: cd backend && python scripts/create_local_admin.py admin YOUR_PASSWORD admin@assetflow.local admin"
fi

# --- 6. Frontend build ---
echo "[5/7] Building frontend..."
cd "$REPO_ROOT"
npm install
npm run build

# --- 7. Deploy frontend and Nginx ---
echo "[6/7] Deploying to Nginx..."
sudo mkdir -p "$WEB_ROOT"
sudo cp -r dist/* "$WEB_ROOT/" 2>/dev/null || sudo cp -r dist/. "$WEB_ROOT/"
sudo chown -R www-data:www-data "$WEB_ROOT"

# Nginx config - preserve HTTPS for wavelync.com when Let's Encrypt certs exist
if [ -f /etc/letsencrypt/live/wavelync.com/fullchain.pem ]; then
  echo "Using HTTPS config (Let's Encrypt certs found)"
  sudo cp "$REPO_ROOT/nginx/nginx-production-https.conf" /etc/nginx/sites-available/${APP_NAME}
  ORIGINS="http://localhost,http://127.0.0.1,http://185.229.226.37,https://185.229.226.37,https://wavelync.com,https://www.wavelync.com,http://wavelync.com,http://www.wavelync.com"
  grep -q ALLOWED_ORIGINS "$REPO_ROOT/backend/.env" 2>/dev/null && sudo sed -i "s|ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=$ORIGINS|" "$REPO_ROOT/backend/.env" || true
else
  echo "Using HTTP config (run scripts/enable_https_wavelync.py after DNS is set for HTTPS)"
  sudo cp "$REPO_ROOT/nginx/nginx-wavelync-http.conf" /etc/nginx/sites-available/${APP_NAME}
fi
# Fix root path in config
sudo sed -i "s|root /var/www/buildingsmanager|root $WEB_ROOT|g" /etc/nginx/sites-available/${APP_NAME}
sudo ln -sf /etc/nginx/sites-available/${APP_NAME} /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
sudo nginx -t && sudo systemctl reload nginx

# --- 7b. Enable HTTPS if certs missing (post-deploy fix) ---
if [ ! -f /etc/letsencrypt/live/wavelync.com/fullchain.pem ]; then
  echo "Obtaining SSL certificates (wavelync.com)..."
  sudo apt-get install -y certbot python3-certbot-nginx 2>/dev/null || true
  if sudo certbot --nginx -d wavelync.com -d www.wavelync.com --non-interactive --agree-tos --register-unsafely-without-email --expand 2>/dev/null; then
    echo "HTTPS enabled."
    ORIGINS="http://localhost,http://127.0.0.1,http://185.229.226.37,https://185.229.226.37,https://wavelync.com,https://www.wavelync.com,http://wavelync.com,http://www.wavelync.com"
    sudo sed -i "s|ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=$ORIGINS|" "$REPO_ROOT/backend/.env"
    # Use production HTTPS config (redirect 80->443)
    sudo cp "$REPO_ROOT/nginx/nginx-production-https.conf" /etc/nginx/sites-available/${APP_NAME}
    sudo sed -i "s|root /var/www/buildingsmanager|root $WEB_ROOT|g" /etc/nginx/sites-available/${APP_NAME}
    sudo nginx -t && sudo systemctl reload nginx
  else
    echo "Certbot skipped (DNS may not point to this server). Use scripts/enable_https_wavelync.py when ready."
  fi
fi

# --- 8. Systemd service for backend ---
echo "[7/7] Installing systemd service..."
sudo tee /etc/systemd/system/assetflow-backend.service > /dev/null << EOF
[Unit]
Description=AssetFlow FastAPI Backend
After=network.target postgresql.service

[Service]
Type=simple
User=$DEPLOY_USER
Group=$DEPLOY_USER
WorkingDirectory=$REPO_ROOT/backend
Environment="PATH=$REPO_ROOT/backend/venv/bin"
ExecStart=$REPO_ROOT/backend/venv/bin/gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker -b 127.0.0.1:8000
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable assetflow-backend
sudo systemctl restart assetflow-backend

echo ""
echo "=========================================="
echo "  Deployment complete!"
echo "=========================================="
echo ""
if [ -f /etc/letsencrypt/live/wavelync.com/fullchain.pem ]; then
  echo "  App URL:    https://wavelync.com  https://www.wavelync.com"
else
  echo "  App URL:    http://185.229.226.37/"
fi
echo "  API docs:   http://185.229.226.37/docs"
echo "  Health:     http://185.229.226.37/health"
echo ""
echo "  Default login: admin / ChangeMe123!"
echo "  CHANGE THE ADMIN PASSWORD after first login!"
echo ""
echo "  Backend logs:  sudo journalctl -u assetflow-backend -f"
echo "  Restart:       sudo systemctl restart assetflow-backend"
echo ""

