-- ============================================================================
-- Remove Test Data Generated by 20250130000000_generate_test_data.sql
-- ============================================================================
-- This migration removes all test data created by the test data generation script.
-- It safely removes only the test records without affecting real data.

-- ============================================================================
-- Step 1: Remove change_log entries for test data
-- ============================================================================
-- Remove change_log entries for test buildings (1000000-1000099)
DELETE FROM change_log
WHERE table_name = 'buildings'
  AND record_id::bigint >= 1000000
  AND record_id::bigint <= 1000099;

-- Remove change_log entries for test assets (1000000000-1000000899)
DELETE FROM change_log
WHERE table_name = 'assets'
  AND record_id::bigint >= 1000000000
  AND record_id::bigint <= 1000000899;

-- ============================================================================
-- Step 2: Remove test assets
-- ============================================================================
-- Remove assets with asset_id in the test range
DELETE FROM assets
WHERE asset_id >= 1000000000
  AND asset_id <= 1000000899;

-- Also remove any assets in test buildings (in case asset_id doesn't match range)
DELETE FROM assets
WHERE building_number >= 1000000
  AND building_number <= 1000099
  AND asset_id >= 1000000000
  AND asset_id <= 1000000899;

-- ============================================================================
-- Step 3: Remove test buildings
-- ============================================================================
-- First, update building total areas to 0 (cleanup)
UPDATE buildings
SET total_building_area = 0
WHERE building_number >= 1000000
  AND building_number <= 1000099;

-- Remove test buildings
DELETE FROM buildings
WHERE building_number >= 1000000
  AND building_number <= 1000099;

-- ============================================================================
-- Step 4: Remove test address entries
-- ============================================================================
-- Remove address entries in the test range (1000-1099)
-- Only if they match the test pattern
DELETE FROM address_list
WHERE street_code >= 1000
  AND street_code <= 1099
  AND street_description LIKE 'רחוב 1%';

-- ============================================================================
-- Step 5: Remove test users (if users table exists)
-- ============================================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users') THEN
    -- Remove test users (but keep the default user)
    DELETE FROM users
    WHERE auth_user_id LIKE 'test-user-%'
       OR (user_email LIKE 'test%@example.com' AND user_name LIKE 'Test User%');
  END IF;
END $$;

-- ============================================================================
-- Step 6: Clean up assets_history for test assets (if exists)
-- ============================================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'assets_history') THEN
    DELETE FROM assets_history
    WHERE asset_id >= 1000000000
      AND asset_id <= 1000000899;
  END IF;
END $$;

-- ============================================================================
-- Step 7: Clean up audit table for test data (if exists)
-- ============================================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'audit') THEN
    -- Remove audit entries for test buildings
    DELETE FROM audit
    WHERE entity_type IN ('building', 'bulk_building')
      AND entity_id ~ '^100000[0-9]{3}$';
    
    -- Remove audit entries for test assets
    DELETE FROM audit
    WHERE entity_type IN ('asset', 'bulk_asset')
      AND entity_id ~ '^1000000[0-9]{3}$';
    
    -- Also check in before_data and after_data JSON
    DELETE FROM audit
    WHERE (
      (before_data::text LIKE '%"building_number":100000%' AND before_data::text LIKE '%"building_number":10000[0-9][0-9]%')
      OR (after_data::text LIKE '%"building_number":100000%' AND after_data::text LIKE '%"building_number":10000[0-9][0-9]%')
      OR (before_data::text LIKE '%"asset_id":1000000%' AND before_data::text LIKE '%"asset_id":1000000[0-9]{3}%')
      OR (after_data::text LIKE '%"asset_id":1000000%' AND after_data::text LIKE '%"asset_id":1000000[0-9]{3}%')
    );
  END IF;
END $$;

-- ============================================================================
-- Summary
-- ============================================================================
-- This script removes:
-- - All change_log entries for test buildings (1000000-1000099)
-- - All change_log entries for test assets (1000000000-1000000899)
-- - All test assets (asset_id: 1000000000-1000000899)
-- - All test buildings (building_number: 1000000-1000099)
-- - Test address entries (street_code: 1000-1099, matching pattern)
-- - Test users (test-user-* and test@example.com)
-- - Test assets_history entries (if table exists)
-- - Test audit entries (if table exists)
--
-- Note: This script is safe to run multiple times (idempotent)


