/*
  # Import Remaining Asset Types (Part 3)
  
  1. Data Import
    - Continue inserting remaining asset types (500-999 series)
*/

INSERT INTO asset_types (name, description, tax_region, elevator, asset_group, single_double_family, penthouse, condo, townhouses, min_size, max_size, shelter) VALUES
('501', 'מוסדות אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('502', 'מוסדות אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('503', 'שכירות עירית נתניה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('504', 'רכוש עירית נתניה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('505', 'מוסד חינוך עירוני', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('506', 'גני נוי עירוניים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('507', 'מוסדות דת', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('508', 'אגודות ספורט', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('509', 'מוסדות אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('510', 'מוסדות אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('511', 'נכסי ממשלה אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('512', 'נכסי ממשלה אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('513', 'מפלגות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('514', 'חלת', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('515', 'ללא סיווג דומה בצו הארנונה אז1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('516', 'ללא סיווג דומה בצו הארנונה אז2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('520', 'מקוואות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('521', 'ישיבות - פנימיות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('522', 'מוסד דת,חינוך ואחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('523', 'מים למוסדות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('552', 'שלט לפי שטח', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('601', 'אדמה חקלאית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('602', 'פרדסים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('603', 'ק.תפוסה תיעול', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('661', 'מיועד לביטול - פרדסים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('662', 'מיועד לביטול - חקלאית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('700', 'קרקע לא בשימוש  עסקים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('701', 'ק.תפוסה לצרכי תעשיה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('702', 'ק.תפוסה לכל מטרה אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('703', 'ק. תפוסה המשמש לעריכת ארועים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('704', 'ק. תפוסה למכירה/השכרה/החסנה וה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('705', 'קרקע תפוסהלשימוש מפעלי בטון וכ', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('800', 'רשת שווק מעל 1000 מ''', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('801', 'בנקים ומוסדות אשראי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('802', 'בתי אריזה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('803', 'תחנות דלק', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('804', 'ק.תפוסה לתחנות דלק', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('805', 'מרכז קניות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('806', 'בתי  קולנוע', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('807', 'גני-ילדים פרטיים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('808', 'בתי אבות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('809', 'דוכן שוק', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('810', 'חניון לרכב מקורה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('811', 'חניון לא מקורה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('812', 'בתי-ספר פרטיים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('813', 'ביס ללא פיקוח מ.חינוך', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('814', 'חניון מעל 15000 מטר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('815', 'חדרי טרנפורמציה חברת החשמל', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('816', 'חניון מקורה לא ראוי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('818', 'שוק וייצמן', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('819', 'דוכן שוק קטן', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('820', 'דוכן שוק חדש', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('821', 'מנהלות מחוז בנקים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('822', 'בנקים תעריף מינימום', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('824', 'חברות ביטוח', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('827', 'מוזיאון למטרת רווח', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('828', 'מוזיאון ללא מטרת רווח', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('881', 'בית אבות אזור 1 מגורים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('882', 'בית אבות אזור 2 מגורים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('883', 'בית אבות אזור 3 מגורים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('901', 'בתי מלון עד 1000 מר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('902', 'בתי מלון מ-1,001 עד 2,000 מר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('903', 'בתי מלון מ-2,001 עד 4,000 מר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('904', 'בתי מלון  מ- 4,001 מטר ומעלה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('905', 'בתי מלון 5 כוכבים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('906', 'דירות מיוחדות מגורים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('907', 'מעון למגורי עולים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('908', 'אולמות כדורת', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('909', 'מרכז ספורט ונופש(קאנטרי קלאב)', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('910', 'מ. ספורט ונופש שטח פתוח', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('911', 'לא פעיל היה קופח כללית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('912', 'מבנה אצטדיון כדורגל', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('913', 'שטח קרקע פתוח של אצטדיון', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('915', 'בתי מלון נכס לא ראוי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('990', 'ביטולים/איחודים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('995', 'נכס לא פעיל', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('999', 'ללא סוג', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
