/*
  # Insert remaining asset types from CSV (codes 501-999)

  1. Changes
    - Add remaining asset types from the CSV file
    - Covers codes from 501 through 999
*/

-- Insert remaining asset types
INSERT INTO asset_types (name, description, tax_region, shared_area_yn, has_elevator, condition_elevator, condition_shared_area, condition_size, min_size, max_size) VALUES
('501', 'מעליות צמוד 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('502', 'מעליות צמוד 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('503', 'מעליות בנייה בנוסף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('504', 'שטח בנייה בנוסף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('505', 'שטח בנייה גולמית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('506', 'בית עלם לכולות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('507', 'מעליות לה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('508', 'מעליות קומתי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('509', 'מעליות צמוד 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('510', 'מעליות צמוד 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('511', 'שטח בנייה צמוד 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('512', 'שטח בנייה צמוד 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('513', 'מרחקת', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('514', 'מב"ט', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('515', 'דיו בנייה צמוד לכלי למצורף גל1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('516', 'דיו בנייה צמוד לכלי למצורף גל2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('520', 'מערכות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('521', 'מעליות - מערכות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('522', 'שטח לה,בנייה צמוד', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('523', 'בית למצורף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('552', 'בית עלם אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('601', 'שטח קומתי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('602', 'מרחקת', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('603', 'מ.חניות בניין', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('661', 'חניות קומתי - גולמי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('662', 'חניות קומתי - גולמי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('700', 'דירת אח במרחק  בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('701', 'מ.חניות בניין בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('702', 'מ.חניות גדל לבית אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('703', 'מ. חניות בניין גולמי גולמית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('704', 'מ. חניות קומתי/מרחקת/חניות לה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('705', 'שטח לכולותות בניין צמוד אזור', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('800', 'דיו שטח לכל 1000 מ', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('801', 'חניות מצורף בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('802', 'דיו בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('803', 'חניות אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('804', 'מ.חניות משותף אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('805', 'שטח בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('806', 'אזור  גולמית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('807', 'אחר-חניות גולמי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('808', 'דיו לבית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('809', 'שטח אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('810', 'חניות קומת בנוסף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('811', 'חניות לא בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('812', 'אחר-דיו גולמית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('813', 'מב"ט בית בנייה מ.חניות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('814', 'חניות גדל 15000 אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('815', 'שטח לכולותות צמוד בנוסף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('816', 'חניות בנייה לא אזור', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('818', 'דיו גולמית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('819', 'שטח גדל אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('820', 'שטח גדל אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('821', 'מעליות צמוד בנוסף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('822', 'חניות בנייה למצורף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('824', 'חניות בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('827', 'מערכות בנייה לבית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('828', 'מערכות גדל לבית אזור', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('881', 'דיו שטח צמוד 1 גולמי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('882', 'דיו שטח צמוד 2 גולמי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('883', 'דיו שטח צמוד 3 גולמי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('901', 'דיו שטח לא 1000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('902', 'דיו שטח מ-1,001 עד 2,000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('903', 'דיו שטח מ-2,001 עד 4,000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('904', 'דיו שטח  מ- 4,001 אזור בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('905', 'דיו שטח 5 גולמית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('906', 'חניות מצורף גולמית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('907', 'שטח גולמי בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('908', 'מעליות בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('909', 'שטח בנייה בנוסף(מעליות צמוד)', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('910', 'מ. חניות בניין גדל אזור', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('911', 'אח קומה גדל אחר"מ בנייה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('912', 'שטח למצורף גולמית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('913', 'דיו שטח צמוד לא למצורף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('915', 'דיו שטח לכל עד לבית', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('990', 'מערכות/מפעילות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('995', 'דיו לא אזור', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('999', 'דיו אחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
