/*
  # Truncate and Import Asset Types from CSV
  
  1. Changes
    - Delete all existing asset types
    - Import all asset types from the provided CSV file
  
  2. Table Structure
    - name (text) - סוג נכס
    - description (text) - תיאור
    - tax_region (integer) - אזור מיסים
    - elevator (text) - מעלית
    - single_double_family (text) - בית פרטי חד משפחתי דו משפחתי
    - penthouse (text) - דירת גג
    - condo (text) - בית משותף
    - townhouses (text) - בניינים צמודי קרקע טוריים מעל 2 יחידות
    - min_size (numeric) - שטח מ
    - max_size (numeric) - שטח עד
*/

-- Truncate the asset_types table
DELETE FROM asset_types;

-- Import all asset types from CSV
INSERT INTO asset_types (name, description, tax_region, elevator, single_double_family, penthouse, condo, townhouses, min_size, max_size) VALUES
('199', 'נכס משולב מגורים', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('202', 'מגורים אזור 1 קו החוף', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('203', 'מגורים אזור 1 קו החוף', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('210', 'מגורים נכס לא ראוי לשימוש', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('211', 'מגורים אזור 1', 10, NULL, NULL, 'כן', NULL, NULL, NULL, NULL),
('211', 'מגורים אזור 1', 10, NULL, 'כן', NULL, NULL, NULL, 100, 9999),
('212', 'מגורים אזור 1', 10, 'כן', NULL, NULL, 'כן', NULL, 110, 9999),
('212', 'מגורים אזור 1', 10, NULL, NULL, NULL, NULL, 'כן', NULL, NULL),
('212', 'מגורים אזור 1', 10, NULL, 'כן', NULL, NULL, NULL, 1, 100),
('213', 'מגורים אזור 1', 10, 'כן', NULL, NULL, 'כן', NULL, 81, 110),
('213', 'מגורים אזור 1', 10, NULL, NULL, NULL, 'כן', NULL, 111, 9999),
('214', 'מגורים אזור 1', 10, 'כן', NULL, NULL, 'כן', NULL, 1, 80),
('214', 'מגורים אזור 1', 10, NULL, NULL, NULL, 'כן', NULL, 1, 110),
('216', 'מרפסת ללא חיוב', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('221', 'מגורים אזור 2', 20, NULL, NULL, 'כן', NULL, NULL, NULL, NULL),
('221', 'מגורים אזור 2', 20, NULL, 'כן', NULL, NULL, NULL, 100, 9999),
('222', 'מגורים אזור 2', 20, 'כן', NULL, NULL, 'כן', NULL, 110, 9999),
('222', 'מגורים אזור 2', 20, NULL, NULL, NULL, NULL, 'כן', NULL, NULL),
('222', 'מגורים אזור 2', 20, NULL, 'כן', NULL, NULL, NULL, 1, 100),
('223', 'מגורים אזור 2', 20, 'כן', NULL, NULL, 'כן', NULL, 81, 110),
('223', 'מגורים אזור 2', 20, NULL, NULL, NULL, 'כן', NULL, 111, 9999),
('224', 'מגורים אזור 2', 20, 'כן', NULL, NULL, 'כן', NULL, 1, 80),
('224', 'מגורים אזור 2', 20, NULL, NULL, NULL, 'כן', NULL, 1, 110),
('226', 'מרפסת ללא חיוב', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('231', 'מגורים אזור 3', 30, NULL, NULL, 'כן', NULL, NULL, NULL, NULL),
('231', 'מגורים אזור 3', 30, NULL, 'כן', NULL, NULL, NULL, 100, 9999),
('232', 'מגורים אזור 3', 30, 'כן', NULL, NULL, 'כן', NULL, 110, 9999),
('232', 'מגורים אזור 3', 30, NULL, NULL, NULL, NULL, 'כן', NULL, NULL),
('232', 'מגורים אזור 3', 30, NULL, 'כן', NULL, NULL, NULL, 1, 100),
('233', 'מגורים אזור 3', 30, 'כן', NULL, NULL, 'כן', NULL, 81, 110),
('233', 'מגורים אזור 3', 30, NULL, NULL, NULL, 'כן', NULL, 111, 9999),
('234', 'מגורים אזור 3', 30, 'כן', NULL, NULL, 'כן', NULL, 1, 80),
('234', 'מגורים אזור 3', 30, NULL, NULL, NULL, 'כן', NULL, 1, 110),
('236', 'מרפסת ללא חיוב', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('241', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('242', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('243', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('244', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('245', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('250', 'מגרש מגורים אזור 1', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('251', 'מגורים אזור 1', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('252', 'מגרש מגורים אזור 2', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('253', 'מגורים אזור 2', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('254', 'מגרש מגורים אזור 3', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('255', 'מגורים אזור 3', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('299', 'נכס משולב מגורים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('300', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('301', 'מגורים מעל 15,000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('302', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('310', 'מגורים נכס לא ראוי לשימוש', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('311', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('312', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('313', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('315', 'מרפסת ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('316', 'מגורים מעל 330 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('317', 'מגורים מעל 330 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('318', 'מגורים מעל 330 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('321', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('322', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('323', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('325', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('390', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('397', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('398', 'מגורים מעל 400 מ"ר קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('399', 'מגורים נכס לא ראוי לשימוש', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('400', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('401', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('402', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('403', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('404', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('405', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('406', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('407', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('408', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('409', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('410', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('411', 'מגורים אזור 4 - קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('412', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('413', 'מגרש מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('414', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('415', 'מגורים אזור 4 קו החוף,מגורים אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('416', 'מגורים אזור 4 קו החוף,מגורים אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('417', 'מגורים אזור 4, קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('501', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('502', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('503', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('504', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('505', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('506', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('507', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('508', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('509', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('510', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('511', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('512', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('513', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('514', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('515', 'מגורים אזור 4 קו החוף אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('516', 'מגורים אזור 4 קו החוף אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('520', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('521', 'מגורים אזור 4 - קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('522', 'מגורים אזור 4,מגורים אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('523', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('552', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('601', 'מגרש מגורים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('602', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('603', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('661', 'מגורים אזור 4 - קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('662', 'מגורים אזור 4 - קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('700', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('701', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('702', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('703', 'מגורים אזור 4 קו החוף אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('704', 'מגורים אזור 4 קו החוף/אזור 1/אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('705', 'מגורים אזור 4 קו החוף אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('800', 'מגורים אזור 4 מעל 1000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('801', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('802', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('803', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('804', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('805', 'מגרש מגורים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('806', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('807', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('808', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('809', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('810', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('811', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('812', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('813', 'מגורים אזור 4 קו החוף אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('814', 'מגורים אזור 4 מעל 15000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('815', 'מגורים אזור 4 קו החוף אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('816', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('818', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('819', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('820', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('821', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('822', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('824', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('827', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('828', 'מגורים אזור 4 קו החוף אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('881', 'מגורים אזור 4 אזור 1 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('882', 'מגורים אזור 4 אזור 2 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('883', 'מגורים אזור 4 אזור 3 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('901', 'מגורים אזור 4 עד 1000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('902', 'מגורים אזור 4 מ-1,001 עד 2,000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('903', 'מגורים אזור 4 מ-2,001 עד 4,000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('904', 'מגורים אזור 4 מ- 4,001 ומעלה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('905', 'מגורים אזור 4 5 קומות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('906', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('907', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('908', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('909', 'מגרש מגורים אזור 4(מגורים אזור 1)', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('910', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('911', 'מגורים אזור 4 קו החוף אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('912', 'מגרש מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('913', 'מגורים אזור 4 אזור 1 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('915', 'מגורים אזור 4 קו החוף', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('990', 'מגורים/מגרש', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('995', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('999', 'מגורים אזור 4', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

