/*
  # Import Remaining Asset Types (Part 2)
  
  1. Data Import
    - Continue inserting remaining asset types
*/

INSERT INTO asset_types (name, description, tax_region, elevator, asset_group, single_double_family, penthouse, condo, townhouses, min_size, max_size, shelter) VALUES
('241', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('242', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('243', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('244', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('245', 'מגורים אזור 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('250', 'מחסן מגורים אזור 1', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('251', 'מגורים אזור 1', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('252', 'מחסן מגורים אזור 2', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('253', 'מגורים אזור 2', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('254', 'מחסן מגורים אזור 3', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('255', 'מגורים אזור 3', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('299', 'נכס משולב עסקים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('300', 'מים בלבד עסקים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('301', 'מסחר מעל 15,000 מר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('302', 'מבנה מכללות ואונברסיטאות', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('310', 'משרדים שרותים ומסחר לא ראוי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('311', 'משרדים שרותים ומסחר אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('312', 'משרדים שרותים ומסחר אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('313', 'משרדי ממשלה אזור 1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('315', 'מסחר ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('316', 'לא ראוי עפי סעיף 330 תעשיה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('317', 'לא ראוי עפי סעיף 330 מסחר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('318', 'לא ראוי עפי סעיף 330 מגורים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('321', 'משרדים שרותים ומסחר אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('322', 'משרדים שרותים ומסחר אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('323', 'משרדי ממשלה אזור 2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('325', 'פינוי בינוי', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('390', 'תיעול איחוד כרטיסים עסקים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('397', 'כרטיס בבניה למעקב עסקים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('398', 'היה בסוג נכס 400 נבדק וחוייבו', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('399', 'תעשיה ומלאכה לא ראוי לשימוש', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('400', 'כרטיס לבניה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('401', 'תעשיה ומלאכה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('402', 'עסיס תעשיה ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('403', 'אורדן תעשיה ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('404', 'תעשית טמפו ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('405', 'גמיד תעשיה ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('406', 'המסלול תעשיה ללא חיו', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('407', 'פרגוד תעשיה ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('408', 'פולידור ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('409', 'צינומנטל ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('410', 'שלרינה תעשיה ללא חיו', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('411', 'מפעלי שנפ - ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('412', 'אביק תעשיה ללא חיוב', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('413', 'נכסי מדינה תעשיה ומלאכה', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('414', 'תעשיה עתירת ידע', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('415', 'נכס המשמש מספרה,קוסמטיקה אזור1', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('416', 'נכס המשמש מספרה,קוסמטיקה אזור2', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('417', 'מפעלי בטון מלט טיט וכו', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
