/*
  # Import Asset Types Part 1

  1. Data Import
    - Insert first batch of asset type records from CSV
*/

INSERT INTO asset_types (name, description, tax_region, shared_area_yn, has_elevator, condition_elevator, condition_shared_area, condition_size, min_size, max_size, notes) VALUES
('199', 'נכס בעירוב בניינים', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('202', 'מחסנים מעל 1 בת ישוב', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('203', 'מחסנים מעל 1 בת ישוב', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('210', 'מחסנים פחות או שווה לשוטח', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('211', 'מחסנים ישוב 1', 10, NULL, 'א', NULL, 'לא', NULL, NULL, NULL, NULL),
('211', 'מחסנים ישוב 1', 10, NULL, 'א', 'לא', NULL, NULL, 100, 9999, NULL),
('212', 'מחסנים ישוב 1', 10, 'כן', 'א', NULL, NULL, 'לא', 110, 9999, NULL),
('212', 'מחסנים ישוב 1', 10, NULL, 'א', NULL, NULL, 'לא', NULL, NULL, NULL),
('212', 'מחסנים ישוב 1', 10, NULL, 'א', 'לא', NULL, NULL, 1, 100, NULL),
('213', 'מחסנים ישוב 1', 10, 'כן', 'א', NULL, NULL, 'לא', 81, 110, NULL),
('213', 'מחסנים ישוב 1', 10, NULL, 'א', NULL, NULL, 'לא', 111, 9999, NULL),
('214', 'מחסנים ישוב 1', 10, 'כן', 'א', NULL, NULL, 'לא', 1, 80, NULL),
('214', 'מחסנים ישוב 1', 10, NULL, 'א', NULL, NULL, 'לא', 1, 110, NULL),
('216', 'שטחים פתח ישוב', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('221', 'מחסנים ישוב 2', 20, NULL, 'א', NULL, 'לא', NULL, NULL, NULL, NULL),
('221', 'מחסנים ישוב 2', 20, NULL, 'א', 'לא', NULL, NULL, 100, 9999, NULL),
('222', 'מחסנים ישוב 2', 20, 'כן', 'א', NULL, NULL, 'לא', 110, 9999, NULL),
('222', 'מחסנים ישוב 2', 20, NULL, 'א', NULL, NULL, 'לא', NULL, NULL, NULL),
('222', 'מחסנים ישוב 2', 20, NULL, 'א', 'לא', NULL, NULL, 1, 100, NULL),
('223', 'מחסנים ישוב 2', 20, 'כן', 'א', NULL, NULL, 'לא', 81, 110, NULL),
('223', 'מחסנים ישוב 2', 20, NULL, 'א', NULL, NULL, 'לא', 111, 9999, NULL),
('224', 'מחסנים ישוב 2', 20, 'כן', 'א', NULL, NULL, 'לא', 1, 80, NULL),
('224', 'מחסנים ישוב 2', 20, NULL, 'א', NULL, NULL, 'לא', 1, 110, NULL),
('226', 'שטחים פתח ישוב', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('231', 'מחסנים ישוב 3', 30, NULL, 'א', NULL, 'לא', NULL, NULL, NULL, NULL),
('231', 'מחסנים ישוב 3', 30, NULL, 'א', 'לא', NULL, NULL, 100, 9999, NULL),
('232', 'מחסנים ישוב 3', 30, 'כן', 'א', NULL, NULL, 'לא', 110, 9999, NULL),
('232', 'מחסנים ישוב 3', 30, NULL, 'א', NULL, NULL, 'לא', NULL, NULL, NULL),
('232', 'מחסנים ישוב 3', 30, NULL, 'א', 'לא', NULL, NULL, 1, 100, NULL),
('233', 'מחסנים ישוב 3', 30, 'כן', 'א', NULL, NULL, 'לא', 81, 110, NULL),
('233', 'מחסנים ישוב 3', 30, NULL, 'א', NULL, NULL, 'לא', 111, 9999, NULL),
('234', 'מחסנים ישוב 3', 30, 'כן', 'א', NULL, NULL, 'לא', 1, 80, NULL),
('234', 'מחסנים ישוב 3', 30, NULL, 'א', NULL, NULL, 'לא', 1, 110, NULL),
('236', 'שטחים פתח ישוב', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('241', 'מחסנים ישוב 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('242', 'מחסנים ישוב 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('243', 'מחסנים ישוב 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('244', 'מחסנים ישוב 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('245', 'מחסנים ישוב 32', 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('250', 'משרד בבניין ישוב 1', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('251', 'מחסנים ישוב 1', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('252', 'משרד בבניין ישוב 2', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('253', 'מחסנים ישוב 2', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('254', 'משרד בבניין ישוב 3', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('255', 'מחסנים ישוב 3', 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('299', 'נכס בעירוב ליברל', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('300', 'נכס מעורב ליברל', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('301', 'מבנה אחסן 15,000 מ"ר', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('302', 'משרד בבניינים לגיטימיים', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('310', 'מחסנים בבניין בחצר או בטור', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);